<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "beneficiary.beneficiary".
 *
 * @property integer $id
 * @property string $beneficiary_no
 * @property integer $branch_id
 * @property integer $company_id
 * @property integer $beneficiary_type_id
 * @property integer $photo_id
 * @property integer $status_id
 * @property string $ktp_no
 * @property string $kk_no
 * @property string $full_name
 * @property string $nickname
 * @property string $birth_place
 * @property string $birth_date
 * @property string $gender
 * @property string $marital_status
 * @property integer $religion
 * @property string $nationality
 * @property string $address
 * @property integer $location_id
 * @property string $hp_no
 * @property string $telephone_no
 * @property integer $last_education_degree_id
 * @property string $job
 * @property string $blood_type
 * @property string $note
 * @property string $metadata
 * @property string $created_stamp
 * @property string $aliasModel
 */
abstract class Beneficiary extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'beneficiary.beneficiary';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['beneficiary_no', 'beneficiary_type_id', 'full_name', 'gender', 'marital_status', 'nationality', 'address', 'location_id', 'job'], 'required'],
            [['branch_id', 'company_id', 'beneficiary_type_id', 'photo_id', 'status_id', 'religion', 'location_id', 'last_education_degree_id'], 'default', 'value' => null],
            [['branch_id', 'company_id', 'beneficiary_type_id', 'photo_id', 'status_id', 'religion', 'location_id', 'last_education_degree_id'], 'integer'],
            [['birth_date', 'created_stamp'], 'safe'],
            [['note', 'metadata'], 'string'],
            [['beneficiary_no'], 'string', 'max' => 20],
            [['ktp_no', 'kk_no', 'nickname', 'birth_place'], 'string', 'max' => 30],
            [['full_name', 'job'], 'string', 'max' => 50],
            [['gender'], 'string', 'max' => 1],
            [['marital_status', 'hp_no', 'telephone_no'], 'string', 'max' => 15],
            [['nationality'], 'string', 'max' => 3],
            [['address'], 'string', 'max' => 100],
            [['blood_type'], 'string', 'max' => 2],
            [['ktp_no'], 'unique'],
            [['beneficiary_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BeneficiaryType::className(), 'targetAttribute' => ['beneficiary_type_id' => 'id']],
            /*[['last_education_degree_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\EducationDegree::className(), 'targetAttribute' => ['last_education_degree_id' => 'id']],
            [['photo_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\File::className(), 'targetAttribute' => ['photo_id' => 'id']],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Status::className(), 'targetAttribute' => ['status_id' => 'id']],*/
            [['branch_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Branch::className(), 'targetAttribute' => ['branch_id' => 'id']],
            /*[['location_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ComLocation::className(), 'targetAttribute' => ['location_id' => 'id']],*/
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'id',
            'beneficiary_no' => 'No Mustahik',
            'branch_id' => 'Cabang',
            'company_id' => 'Lembaga',
            'beneficiary_type_id' => 'Tipe Asnaf',
            'photo_id' => 'Foto',
            'status_id' => 'Status',
            'ktp_no' => 'No KTP',
            'kk_no' => 'No KK',
            'full_name' => 'Nama Lengkap',
            'nickname' => 'Nama Panggilan',
            'birth_place' => 'Tempat Lahir',
            'birth_date' => 'Tanggal Lahir',
            'gender' => 'Jenis Kelamin (L/P)',
            'marital_status' => 'Status Perkawinan',
            'religion' => 'Agama',
            'nationality' => 'Kewarganegaraan',
            'address' => 'Alamat',
            'location_id' => 'Lokasi',
            'hp_no' => 'No HP',
            'telephone_no' => 'No Telepon',
            'last_education_degree_id' => 'Pendidikan Terakhir',
            'job' => 'Pekerjaan',
            'blood_type' => 'Gol. Darah',
            'note' => 'Catatan',
            'metadata' => 'Metadata',
            'created_stamp' => 'Waktu Input',
        ];
    }




}
