<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "com_country".
 *
 * @property integer $id
 * @property string $country_name
 * @property string $country_code
 * @property string $country_code3d
 * @property string $country_prefix
 * @property string $aliasModel
 */
abstract class Country extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'com_country';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['country_name'], 'string', 'max' => 100],
            [['country_code'], 'string', 'max' => 2],
            [['country_code3d'], 'string', 'max' => 3],
            [['country_prefix'], 'string', 'max' => 7],
            [['country_code'], 'unique'],
            [['country_name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'country_name' => 'Country Name',
            'country_code' => 'Country Code',
            'country_code3d' => 'Country Code3d',
            'country_prefix' => 'Country Prefix',
        ];
    }




}
