<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pdg.project".
 *
 * @property integer $id
 * @property string $project_name
 * @property integer $percent_activity
 * @property integer $percent_financial
 * @property integer $branch_id
 * @property string $start
 * @property string $finish
 * @property integer $budget_id
 * @property double $budget_amount
 * @property double $balance
 * @property integer $currency_id
 * @property integer $created_by
 * @property string $created_stamp
 * @property integer $updated_by
 * @property string $updated_stamp
 * @property string $notes
 * @property string $accountno
 * @property string $currency_code
 * @property integer $program_id
 * @property string $program
 * @property integer $location_id
 * @property string $location_name
 * @property string $search
 * @property integer $beneficiary_total
 * @property integer $non_qol
 * @property integer $qol_1
 * @property integer $qol_2
 * @property integer $qol_3
 * @property integer $qol_4
 * @property integer $qol_5
 * @property integer $qol_6
 * @property integer $qol_total
 * @property string $department
 * @property integer $project_qol_summary_id
 * @property string $product_name
 * @property string $realize_date_start
 * @property string $realize_date_finish
 * @property integer $year
 * @property integer $project_class_id
 * @property integer $status_id
 * @property string $project_no
 * @property integer $pic_id
 * @property string $project_date
 * @property string $execute_date
 * @property string $pic_name
 * @property string $created_ip
 * @property string $updated_ip
 * @property integer $partner_id
 * @property double $amount
 * @property integer $quantity
 * @property string $fep_date
 * @property string $start_baseline
 * @property string $finish_baseline
 * @property string $start_actual
 * @property string $finish_actual
 * @property integer $start_variance
 * @property integer $finish_variance
 * @property string $revision_no
 * @property string $beneficiary_data_type
 * @property integer $cpm_id
 * @property string $address
 * @property integer $report_complete
 * @property string $description
 * @property string $program_overview
 * @property string $report_upload_stamp
 * @property string $report_download_stamp
 * @property string $items_verifyqaqc
 * @property string $items_closedqaqc
 * @property string $start_report_baseline
 * @property string $start_report_realize
 * @property string $start_report_actual
 * @property integer $country_id
 * @property string $closed_date
 * @property integer $report_plan
 * @property integer $verified_by
 * @property integer $company_id
 * @property string $recipients
 * @property string $revisi_comment
 * @property double $budget_amount_real 
 * 
 * @property \app\models\ProjectBudget[] $projectBudgets 
 * @property \app\models\ProjectIpp[] $projectIpps 
 * @property \app\models\ProjectReport[] $projectReports 
 * @property \app\models\ProjectVerify[] $projectVerifies 
 * @property string $aliasModel
 */
abstract class Project extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pdg.project';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['percent_activity', 'percent_financial', 'branch_id', 'budget_id', 'currency_id', 'created_by', 'updated_by', 'program_id', 'location_id', 'beneficiary_total', 'non_qol', 'qol_1', 'qol_2', 'qol_3', 'qol_4', 'qol_5', 'qol_6', 'qol_total', 'project_qol_summary_id', 'year', 'project_class_id', 'status_id', 'pic_id', 'partner_id', 'quantity', 'start_variance', 'finish_variance', 'cpm_id', 'report_complete', 'country_id', 'report_plan', 'verified_by', 'company_id'], 'integer'],
            [['start', 'finish', 'created_stamp', 'updated_stamp', 'realize_date_start', 'realize_date_finish', 'project_date', 'execute_date', 'fep_date', 'start_baseline', 'finish_baseline', 'start_actual', 'finish_actual', 'report_upload_stamp', 'report_download_stamp', 'start_report_baseline', 'start_report_realize', 'start_report_actual', 'closed_date'], 'safe'],
            [['budget_amount', 'balance', 'amount', 'budget_amount_real'], 'number'],
            [['notes', 'program', 'location_name', 'search', 'description', 'program_overview', 'items_verifyqaqc', 'items_closedqaqc', 'recipients'], 'string'],
            [['project_name'], 'string', 'max' => 100],
            [['accountno'], 'string', 'max' => 30],
            [['currency_code'], 'string', 'max' => 5],
            [['department'], 'string', 'max' => 64],
            [['product_name', 'pic_name'], 'string', 'max' => 128],
            [['project_no'], 'string', 'max' => 32],
            [['created_ip', 'updated_ip'], 'string', 'max' => 15],
            [['revision_no'], 'string', 'max' => 10],
            [['beneficiary_data_type'], 'string', 'max' => 1],
            [['address'], 'string', 'max' => 1024],
            [['revisi_comment'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'project_name' => 'Nama Proyek',
            'percent_activity' => 'Percent Activity',
            'percent_financial' => 'Percent Financial',
            'branch_id' => 'Cabang',
            'start' => 'Start',
            'finish' => 'Tanggal Selesai',
            'budget_id' => 'Budget ID',
            'budget_amount' => 'Budget Amount',
            'balance' => 'Balance',
            'currency_id' => 'Currency ID',
            'created_by' => 'Dibuat Oleh',
            'created_stamp' => 'Created Stamp',
            'updated_by' => 'Update Oleh',
            'updated_stamp' => 'Updated Stamp',
            'notes' => 'Ruang Lingkup Pekerjaan (Scope)',
            'accountno' => 'Accountno',
            'currency_code' => 'Currency Code',
            'program_id' => 'Program',
            'program' => 'Program',
            'location_id' => 'Lokasi',
            'location_name' => 'Alamat',
            'search' => 'Search',
            'beneficiary_total' => 'Beneficiary Total',
            'non_qol' => 'Non Qol',
            'qol_1' => 'Qol 1',
            'qol_2' => 'Qol 2',
            'qol_3' => 'Qol 3',
            'qol_4' => 'Qol 4',
            'qol_5' => 'Qol 5',
            'qol_6' => 'Qol 6',
            'qol_total' => 'Qol Total',
            'department' => 'Department',
            'project_qol_summary_id' => 'Project Qol Summary ID',
            'product_name' => 'Product Name',
            'realize_date_start' => 'Tanggal Rencana Eksekusi',
            'realize_date_finish' => 'Tanggal Rencana Selesai Eksekusi',
            'year' => 'Year',
            'project_class_id' => 'Project Class ID',
            'status_id' => 'Status',
            'project_no' => 'No PMP',
            'pic_id' => 'Penanggung Jawab',
            'project_date' => 'Tanggal PMP',
            'execute_date' => 'Tanggal Eksekusi',
            'pic_name' => 'Pic Name',
            'created_ip' => 'Created Ip',
            'updated_ip' => 'Updated Ip',
            'partner_id' => 'Mitra',
            'amount' => 'Nilai',
            'quantity' => 'Jumlah Paket',
            'fep_date' => 'Fep Date',
            'start_baseline' => 'Tanggal Permintaan Eksekusi',
            'finish_baseline' => 'Tanggal Permintaan Eksekusi Finish',
            'start_actual' => 'Tanggal Aktual Eksekusi',
            'finish_actual' => 'Tanggal Aktual Eksekusi Finish',
            'start_variance' => 'Start Variance',
            'finish_variance' => 'Finish Variance',
            'revision_no' => 'Revision No',
            'beneficiary_data_type' => 'Jenis Inputan Penerima Manfaat',
            'cpm_id' => 'CPM',
            'address' => 'Address',
            'report_complete' => 'Report Complete',
            'description' => 'Deskripsi Program',
            'program_overview' => 'Gambaran Wilayah Program',
            'report_upload_stamp' => 'Tanggal Upload Laporan',
            'report_download_stamp' => 'Tanggal Terakhir Download Laporan',
            'items_verifyqaqc' => 'Items Verifyqaqc',
            'items_closedqaqc' => 'Items Closedqaqc',
            'start_report_baseline' => 'Tanggal Permintaan Pelaporan',
            'start_report_realize' => 'Tanggal Rencana Pelaporan',
            'start_report_actual' => 'Tanggal Aktual Pelaporan',
            'country_id' => 'Country ID',
            'closed_date' => 'Tanggal Close Project',
            'report_plan' => 'Tipe Rencana Pelaporan',
            'verified_by' => 'Verified By',
            'company_id' => 'Company ID',
            'recipients' => 'Recipients',
            'revisi_comment' => 'Revisi Comment',
            'budget_amount_real' => 'Budget Amount Real', 
        ];
    }
}
