<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pdg.project__beneficiary".
 *
 * @property integer $id
 * @property integer $is_detail
 * @property integer $project_id
 * @property integer $beneficiary_type_id
 * @property integer $beneficiary_asnaf_id
 * @property integer $pillar_id
 * @property integer $beneficiary_id
 * @property integer $total_pm
 * @property string $status_id
 * @property integer $created_by
 * @property string $created_name
 * @property string $created_stamp
 * @property string $aliasModel
 */
abstract class ProjectBeneficiary extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pdg.project__beneficiary';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_detail', 'project_id', 'beneficiary_type_id', 'beneficiary_asnaf_id', 'pillar_id', 'beneficiary_id', 'total_pm', 'created_by'], 'default', 'value' => null],
            [['is_detail', 'project_id', 'beneficiary_type_id', 'beneficiary_asnaf_id', 'pillar_id', 'beneficiary_id', 'total_pm', 'created_by'], 'integer'],
            [['created_stamp'], 'safe'],
            [['status_id'], 'string', 'max' => 15],
            [['created_name'], 'string', 'max' => 125],
            [['beneficiary_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Beneficiary::className(), 'targetAttribute' => ['beneficiary_id' => 'id']],
            [['beneficiary_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BeneficiaryType::className(), 'targetAttribute' => ['beneficiary_type_id' => 'id']],
            [['project_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Project::className(), 'targetAttribute' => ['project_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_detail' => 'Is Detail',
            'project_id' => 'Project ID',
            'beneficiary_type_id' => 'Beneficiary Type ID',
            'beneficiary_asnaf_id' => 'Beneficiary Asnaf ID',
            'pillar_id' => 'Pillar ID',
            'beneficiary_id' => 'Beneficiary ID',
            'total_pm' => 'Total Pm',
            'status_id' => 'Status ID',
            'created_by' => 'Created By',
            'created_name' => 'Created Name',
            'created_stamp' => 'Created Stamp',
        ];
    }




}
